# Jekyll Configuration File
# www.jeff.wilcox.name

base_url: http://www.jeff.wilcox.name
#base_url: /

description: "The blog of Jeff Wilcox: Windows Phone, Windows Azure, Microsoft and open source technology by software developer Jeff Wilcox at Microsoft."
root_desc: "Jeff Wilcox is a Principal Software Development Engineer at Microsoft."

markdown: rdiscount
rdiscount:
    extensions:
        - generate_toc
#pygments: false

highlighter: rouge

# Conforms to the same original WordPress format that I was using.
permalink:	/:year/:month/:title/

exclude: ['Rakefile', 'README.textile', 'server.bat']

# Custom variables I use to define my primary and secondary CDN endpoints.
cdn: //az414997.vo.msecnd.net/waz/
